travis:
  secure:
    BINSTAR_TOKEN: VOX7jwR8AexWRWXOO/PK4nCliI+Z0uVRDrVUZU/1LYCc4ruKnGoHtcJDiwV4HoUDtpgY+0Vad0harStGf2xwv9ZPnMrNpbXsTGNv/MK0QoRl3zbl7os2myThP3L6AYZ3cwuqMwwEGPCxH1xfxcbcJlBDg1RKRjos9I365Sl0BkagyjmYC0m1KCR/bSyKvlRYVilTlyleoNXr8uaskNuw1WHN2gJZbvwhHV3FaUHcZVbh+gVQiuauxdA6uCaj+OQ7OIeG1Ay3b0qqJP5OvUPrLktygzmayMVXInSc+LdpWrvApSjJqjohzMzg6/ixQlnmwP4aB3kDNxTGL43Nz5sy3BFgNZR2BT3B+ndNfO5j0VP2/loRWpPtaRizcW8v1VwEF2hPgzg1gqQW469tQzZHtLDIpkIDYc9/WEd7SSMZX5w8CGFjAY6gk28oCE1KdcDvJYdpoJQVgLI9OkYcPBf2GmR/yLUSq1KMEpXLpK9LE1ENbYH4HZYVqKZDZOv36HbsEzGGfBU8kGF4gScpWnAaJeQcfGJAFZXspdveCttM5egxQh0glmsscJmT+JbtZMFLTY8565oByXqX4kfrxi6pFLpVzcei/oLGHvsoFR7fHMhn8uNvSKs1NWf+rRCs82FU9ghmbSvEpuoM1f9oGUbhc0908Vcwx50/WNSqRa4ruX8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
